ELiconaExamenAeroMexico/PL/Controllers/PasajeroController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Cryptography;
using System.Net.Mail;
using System.Web;

namespace PL.Controllers
{
    public class PasajeroController : Controller
    {
		[HttpGet]
		public ActionResult Login()
		{

			ML.Pasajero usuario = new ML.Pasajero();
			return View(usuario);
		}

		[HttpPost]
		public ActionResult Login(ML.Pasajero usuario, string password)
		{

			var bcrypt = new Rfc2898DeriveBytes(password, new byte[0], 10000, HashAlgorithmName.SHA256);

			var passwordHash = bcrypt.GetBytes(20);

			if (usuario.UserName != null)
			{

				usuario.Password = passwordHash;
				ML.Result result = BL.Pasajero.Add(usuario);
				return View();
			}
			else
			{

				ML.Result result = BL.Pasajero.GetByUserName(usuario.Correo);
				//usuario = (ML.Login)result.Object;
				if (result.Correct)
				{
					usuario = (ML.Pasajero)result.Object;
					if (usuario.Password.SequenceEqual(passwordHash))
					{
						ViewBag.Message = "Acceso Permitido";
						return RedirectToAction("Index", "Home");
					}
					else
					{
						ViewBag.Message = "Contraseña Invalida";
						return PartialView("ModalLogin");
					}
				}

				else
				{
					ViewBag.Message = "Usuario Invalido";
					return PartialView("ModalLogin");


				}
			}

		}
	}
}

ELiconaExamenAeroMexico/PL/Views/Pasajero/Login.cshtml
@model ML.Pasajero
@{
    ViewData["Title"] = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>

<head>
	<title>Welcome</title>
	<link rel="stylesheet" href="/css/Login.css">
	<link href="https://fonts.googleapis.com/css2?family=Jost:wght@500&display=swap" rel="stylesheet">
	<label>Login</label>
</head>


<div class="login-wrap">
	<div class="login-html">
		<input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Sign In</label>
		<input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">Sign Up</label>
		<div class="login-form">

			<div class="sign-in-htm">

				@using (Html.BeginForm("Login", "Pasajero", FormMethod.Post, new { enctype = "multipart/form-data" }))
				{
					<div class="group">
						<label for="user" class="label" required="">Correo Electronico</label>
						<input name="Correo" id="Correo" type="text" class="input" required="">
					</div>
					<div class="group">
						<label for="pass" class="label" required="">Password</label>
						<input name="Password" id="Password" type="password" class="input" data-type="password" required="">
					</div>
					@*<div class="group">
				<input id="check" type="checkbox" class="check" checked>
				<label for="check"><span class="icon"></span> Keep me Signed in</label>
				</div>*@
					<div class="group">
						<input type="submit" class="button" value="Sign In">
					</div>
					@*<div class="hr"></div>*@
					@*<div class="foot-lnk">
				<a href="#forgot">Forgot Password?</a>
				</div>*@
				}
			</div>


			<div class="sign-up-htm">

				@using (Html.BeginForm("Login", "Pasajero", FormMethod.Post, new { enctype = "multipart/form-data" }))
				{

					<div class="group">
						<label for="user" class="label" required="">Nombre</label>
						<input name="Nombre" id="Nombre" type="text" class="input" required="">
					</div>

					<div class="group">
						<label for="user" class="label" required="">Apellido Paterno</label>
						<input name="ApellidoPaterno" id="ApellidoPaterno" type="text" class="input" required="">
					</div>

					<div class="group">
						<label for="user" class="label" required="">Apellido Materno</label>
						<input name="ApellidoMaterno" id="ApellidoMaterno" type="text" class="input" required="">
					</div>


					<div class="group">
						<label for="user" class="label" required="">User Name</label>
						<input name="UserName" id="Username" type="text" class="input" required="">
					</div>

					<div class="group">
						<label for="pass" class="label" required="">Correo Electronico</label>
						<input name="Correo" id="Correo" type="email" class="input" required="">
					</div>

					<div class="group">
						<label for="pass" class="label" required="">Password</label>
						<input name="Password" id="Password" type="password" class="input" data-type="password" required="">
					</div>
					@*<div class="group">
				<label for="pass" class="label">Repeat Password</label>
				<input id="pass" type="password" class="input" data-type="password">
				</div>*@


					<div class="hr"></div>

					<div class="group">
						<input type="submit" class="button" value="Sign Up">
					</div>
				}


				<div class="foot-lnk">
					<label for="tab-1">Ya Estas Registrado?</a>
				</div>


			</div>
		</div>
	</div>
</div>

</html>

ELiconaExamenAeroMexico/PL/Views/Pasajero/ModalLogin.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "Login", "Pasajero", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>